server:
  port: ${USER_SERVICE_PORT}

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:${USER_SERVICE_DB_PORT}/${DB_NAME:user_db}
    username: ${USER_SERVICE_DB_USERNAME:Username}
    password: ${USER_SERVICE_DB_PASSWORD:Password}

  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_SECRET_PASSWORD:redis_password}
      entity-ttl: 60

  jpa:
    show-sql: ${SHOW_SQL:true}

crypto:
  card-secret-key: "${CARD_SECRET_KEY:hfdgchtxbfjvyubjvdsfsdgfdfhgjegj}"

logging:
  level:
    root: DEBUG
